### ISSUE TITLE
Set outputs for plugin-test action

### ISSUE THREAD

**Issue by kameshsampath** [asdf-vm/actions#330]
As a developer I would like to have the  output from the plugin test command to validate my  test results as part of the workflow.  The improvement to the plugin action could be like:

```yaml
...
outputs:
  stdout:
    description: "An array of stdout lines the test command"
  stderr:
    description: "An array of stderr of the test command"
  debug:
    description: "An array of debug lines of the test command"
```

The output essentially are the lines from the `exec.exec(...)`
