### ISSUE TITLE
Install action fails if asdf is already installed

### ISSUE THREAD

**Issue by abatilo** [asdf-vm/actions#356]
If the correct version is already installed, then I think this action shouldn't fail.

When installing asdf using this action to github action runners, asdf will get installed to a shared directory that isn't wiped and ultimately fails the workflow.

**Comment by skyqrose** [comment]
I ran into this problem when doing a partial cache restore. When I edit my `.tool-versions`, I want to install only the changed values. When the cache `restore-keys` causes a partial hit, `asdf-vm/actions/install` fails with

```
Run asdf-vm/actions/install@v1
  with:
    asdf_branch: master
Cloning asdf into ASDF_DIR: /home/runner/.asdf
/usr/bin/git clone --depth 1 --branch master https://github.com/asdf-vm/asdf.git /home/runner/.asdf
fatal: destination path '/home/runner/.asdf' already exists and is not an empty directory.
Error: Action failed with error Error: The process '/usr/bin/git' failed with exit code 128
```

Because of this, I can't use cache `restore-keys`, and have to do a completely fresh install of all plugins whenever any one of them changes.

Excerpt from my workflow steps:
```
      # cache the asdf directory, using the values from .tool-versions
      - name: asdf cache
        uses: actions/cache@v2
        with:
          path: ~/.asdf
          key: cache-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: cache-asdf-
        id: asdf-cache
      # only run `asdf install` if we didn't hit the cache
      - uses: asdf-vm/actions/install@v1
        if: steps.asdf-cache.outputs.cache-hit != 'true'
```
