### ISSUE TITLE
Add the ability to install only particular tools

### ISSUE THREAD

**Issue by ibratoev** [asdf-vm/actions#401]
Currently, the `install` command installs all the tools defined in `.tool-versions`.
In certain CI workflows, you may need only a subset of the tools. Allow installing only the specified tools.

**Comment by jonath92** [comment]
I am also looking forward to this. As a workaround I have created the following custom action, which installs and caches a single asdf plugin. 

```yml
name: "Install asdf"
description: "Installs asdf"

inputs:
  plugin:
    description: "The asdf plugin to install. Must be set in ./.tool-versions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Determine plugin version
      shell: bash
      id: determine_version
      run: echo "version=$(grep '^${{ inputs.plugin }}' ./.tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT

    - name: cache asdf
      id: cache-asdf
      uses: actions/cache@v3
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-asdf-${{ inputs.plugin }}-${{ steps.determine_version.outputs.version }}

    - name: setup asdf
      if: steps.cache-asdf.outputs.cache-hit != 'true'
      uses: asdf-vm/actions/setup@v2

    - name: Install asdf plugin
      shell: bash
      if: steps.cache-asdf.outputs.cache-hit != 'true'
      run: |
        asdf plugin add ${{ inputs.plugin }}
        asdf install ${{ inputs.plugin }} ${{ steps.determine_version.outputs.version }}
```

You can test use it inside your workflow by: 
```yaml
name: build
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache and install java
        uses: ./.github/actions/install-and-cache-asdf-plugins
        with:
          plugin: java
```
