### ISSUE TITLE
The action doesn't work when we cache the `/home/runner/.asdf` folder with Github Cache action

### ISSUE THREAD

**Issue by andyduong1920** [asdf-vm/actions#445]
Hi all, thank you for creating this action.

### Problem 

We are starting to use this action on our CI workflow; it's working well. The only issue is we can't cache the `asdf` directory to reduce the installation time.

The installation step takes more than 3 minutes.

![image](https://user-images.githubusercontent.com/11751745/168982773-7d9fc213-989d-4a73-b0fe-d96e266fcb9e.png)

We tried to cache that with the Github cache feature by caching the `/home/runner/.asdf` folder. It ends up with the following error.

![image](https://user-images.githubusercontent.com/11751745/168983011-92d977ef-6634-4a86-9662-fe3cb43ce2f2.png)

### Expectation

The action should work with the Github cache. If the `asdf or plugins` exist in `/home/runner/.asdf`. Install them directly.

**Comment by andyduong1920** [comment]
Just an update we just figure out 1 work around way following https://github.com/asdf-vm/actions/issues/235#issuecomment-862358821

![image](https://user-images.githubusercontent.com/11751745/168992372-b8936929-8d41-40ca-aa3b-5826a2bf4548.png)

**Comment by andyduong1920** [comment]
Just an update, we could also remove the `if: steps.asdf-cache.outputs.cache-hit != 'true'` there, the `asdf-vm/actions/install@v1` could determine which plugin has been installed

![image](https://user-images.githubusercontent.com/11751745/168996918-726a33c5-ad57-4882-aabb-3b62a2008628.png)

**Comment by andyduong1920** [comment]
Our final solution so far

```
- name: Setup asdf
  uses: asdf-vm/actions/setup@v1

- name: Cache asdf
  uses: actions/cache@v2
  with:
    path: |
      /home/runner/.asdf
    key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
    restore-keys: |
      ${{ runner.os }}-asdf-

- name: Install dependencies in .tool-versions
  uses: asdf-vm/actions/install@v1
```
