### ISSUE TITLE
Install with `tools` (only allowlisted tools, with versions from `.tool-versions`)

### ISSUE THREAD

**Issue by MPV** [asdf-vm/actions#566]
What do we think about the idea of adding support for something like this:

```bash
$ cat .tool-versions
action-validator 0.5.3
gcloud 1.2.3
```
```yaml
[...]
steps:
  - uses: action/checkout@v4
  - uses: asdf-vm/actions/install@v2
    with:
      tools: |
        action-validator
```
...and then it would only `asdf install action-validator 0.5.3` (and not `gcloud`).

My hope is that this could simplify/speed up many jobs where you only need one particular tool for the thing you want to run.

**Comment by gvkhna** [comment]
Here's a simple workaround:

```yml
      - name: Install asdf
        uses: asdf-vm/actions/setup@v3
      - name: Install asdf plugins
        uses: asdf-vm/actions/plugins-add@v3
      - name: Install asdf tools
        run: |
          asdf install nodejs
          asdf install python
```

Just list what you need installed manually like so
