### ISSUE TITLE
windows-latest test broken

### ISSUE THREAD

**Issue by sarg3nt** [asdf-vm/actions#582]
Attempting to use `windows-latest` in a github action to test my plugin and it fails.
asdf appears to install but then is not found.

I'm new to github actions so it's entirely possible I'm doing something wrong.

## `build.yaml`

```yaml
name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      fail-fast: false
      matrix:
        os:
          # See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
          - ubuntu-latest
          - windows-latest # broken
          - macos-12 # Intel
          #- macos-latest # m1, not supported by tealdeer yet.
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: tldr --version
```

## Output

```
Run asdf-vm/actions/plugin-test@v3
  with:
    command: tldr --version
    version: latest
    asdf_branch: master
    skip_install: false
    github_token: ***
Test plugin
  Cloning asdf into ASDF_DIR "C:\Users\runneradmin\.asdf" on branch "master"
  "C:\Program Files\Git\bin\git.exe" clone --depth 1 --branch master --single-branch https://github.com/asdf-vm/asdf.git C:\Users\runneradmin\.asdf
  Cloning into 'C:\Users\runneradmin\.asdf'...
  Error: Action failed with error Error: Unable to locate executable file: asdf. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```
