### ISSUE TITLE
"No version is set for command escript": rebar3 after Erlang

### ISSUE THREAD

**Issue by kivra-pauoli** [asdf-vm/actions#585]
👋 I'm trying to use this action to install `rebar3` alongside Erlang/OTP, in order to replicate "remote as local CI", which is something I think `asdf` targets as a goal. The action works almost without issue, but when installing `rebar3` I get the error above (PR title): https://github.com/kivra-pauoli/asdf-vm-actions-test/actions/runs/10817651535/job/30011488522#step:3:53. This is from an example repo I created where you can see there's nothing fancy being done.

`.tool-versions` is

```
actionlint 1.7.1
markdownlint-cli2 0.14.0
yamllint 1.35.1
erlang 27.0.1
rebar 3.24.0
```

GitHub workflow is

```
---
"on":
  push:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: asdf-vm/actions/install@v3.0.2
```

At this moment I don't know if this is:

* an action issue
* an `asdf` issue
* a plugin-specific issue (it would be in `rebar3`, I guess, since Erlang/OTP installs Ok)
* a plugin dependency issue (I don't know how `asdf` handles the dependency tree in the case of `rebar3` requiring Erlang/OTP)

Is there a quick hack for this to work as it should?

I've otherwise created a script that would read `.tool-versions` and install+reshim each tool before moving to the next one, but this also doesn't seem to solve it.

Thanks for your help.
