### ISSUE TITLE
Support custom paths for `.tool-versions`

### ISSUE THREAD

**Issue by DimitriosNaikopoulos** [asdf-vm/actions#586]
What do you think about supporting a GHA option to use a different file than the default `.tool-versions` ? 

Example: 

```
...
steps:
  - uses: action/checkout@v4
  - uses: asdf-vm/actions/install@v2
     with:
          tool-versions-path: ./my/custom/path/.tool-versions 
```

or

```
...
steps:
  - uses: action/checkout@v4
  - uses: asdf-vm/actions/install@v2
     with:
          tool-versions-path: ./tool-versions.ci
```

This will allow users to manage tools differently in CI to avoid installing unnecessary development dependencies that someone may only need on their local machine.

Do you think that could be possible?

Thanks 😄
