### ISSUE TITLE
Unable to resolve v4.0.2: reference not found

### ISSUE THREAD

**Issue by skf-funzt** [asdf-vm/actions#594]
The current README.md on `master` references `v4` which is not yet released.
This let actions fail with

```
Unable to resolve v4.0.2: reference not found
```

The current solution is to revert to `v3` or `v3.0.2`

Issue introduced by #590

**Comment by blimmer** [comment]
You can also pin to a git commit SHA, as well:

```yml
- name: Setup ASDF VM
  # TODO: use @v4 when released https://github.com/asdf-vm/actions/issues/594
  uses: asdf-vm/actions/setup@9cd779f40fe38688dd19505ccbc4eaaf018b44e7
  with:
    asdf_version: v0.16.7
```

**Comment by skf-funzt** [comment]
> You can also pin to a git commit SHA, as well:
> 
> - name: Setup ASDF VM
>   # TODO: use @v4 when released https://github.com/asdf-vm/actions/issues/594
>   uses: asdf-vm/actions/setup@9cd779f40fe38688dd19505ccbc4eaaf018b44e7
>   with:
>     asdf_version: v0.16.7

Thank you very much. I forgot about that.

**Comment by project0** [comment]
@jthegedus can you create a proper tag release?

**Comment by yarokon** [comment]
> You can also pin to a git commit SHA, as well:
> 
> ```yaml
> - name: Setup ASDF VM
>   # TODO: use @v4 when released https://github.com/asdf-vm/actions/issues/594
>   uses: asdf-vm/actions/setup@9cd779f40fe38688dd19505ccbc4eaaf018b44e7
>   with:
>     asdf_version: v0.16.7
> ```
> 

Currently, `asdf_version` should be used without 'v' at the beginning. Here is [code reference](https://github.com/asdf-vm/actions/pull/590/files#diff-b9fee35d2f064eea47842b61bf70c528b7cd4483596c0c63fd9afd844058d8f2R71-R73).

```yaml
    - name: Install asdf
      uses: asdf-vm/actions/install@9cd779f40fe38688dd19505ccbc4eaaf018b44e7
      with:
        asdf_version: 0.16.7 # In the future the format could be changed to v0.16.7
```

@Dabolus, could you please check if this intentional?
