### ISSUE TITLE
How do I add plugins that are not part of the `asdf-plugins` repository?

### ISSUE THREAD

**Issue by abatilo** [asdf-vm/actions#70]
If I make my own `asdf` plugin, and I want to reference it in my `.tool-version`, how do I have the GH Actions know which repository to clone?

**Comment by imbsky** [comment]
You should be able to install it as described in the README.

Add asdf plugin

```yml
steps:
  - name: Add <NAME>
    run: asdf plugin add <NAME> <GIT URL>
```

Install your `.tool-versions` tools

```yml
steps:
  - name: asdf_install
    uses: asdf-vm/actions/install@v1
```

**Comment by abatilo** [comment]
This doesn't appear to work:

```
 
name: asdf
on: push

jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: asdf setup
        uses: asdf-vm/actions/setup@v1.0.0
      - name: asdf plugin add
        run: |
          asdf plugin add aws-iam-authenticator https://github.com/stefansedich/asdf-aws-iam-authenticator
      - name: asdf install
        uses: asdf-vm/actions/install@v1
```

https://github.com/abatilo/asdf-action-demo/runs/814402543#step:5:10

The `install` action tries to add all the plugins again and fails

**Comment by imbsky** [comment]
Indeed...

**Comment by vic** [comment]
What about using `before_install` and doing `asdf plugin add ...` in there ? 

https://github.com/asdf-vm/actions/blob/master/install/action.yml#L14

**Comment by superbrothers** [comment]
@abatilo This workflow works correctly.

```yaml
name: asdf
on: push

jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: asdf setup
        uses: asdf-vm/actions/setup@v1.0.0
      - name: asdf install
        run: |
          set -x
          asdf plugin add aws-iam-authenticator https://github.com/stefansedich/asdf-aws-iam-authenticator
          asdf install
          asdf exec aws-iam-authenticator help
```
- https://github.com/superbrothers-sandbox/try-asdf-action/runs/815450840
